---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/pivotal-enablement/attendee-service
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: pivot-twhitney
    space: pal
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service/ci/tasks/test.yml
- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: build-artifacts/attendee-service.jar
